<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity]
#[ORM\Table(name: 'admin_tasks')]
class AdminTask
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue]
    private int $id;

    #[ORM\Column(type: 'string', length: 180)]
    private string $title;

    #[ORM\Column(type: 'text', nullable: true)]
    private string|null $description = null;

    #[ORM\Column(type: 'string')]
    private string $status = 'TODO';

    #[ORM\Column(type: 'string')]
    private string $priority = 'MEDIUM';

    #[ORM\Column(type: 'string', length: 180, nullable: true)]
    private string|null $tags = null;

    #[ORM\Column(name: 'due_date', type: 'date', nullable: true)]
    private \DateTimeInterface|null $dueDate = null;

    #[ORM\Column(name: 'stars_earned', type: 'integer')]
    private int $starsEarned = 0;

    #[ORM\Column(name: 'completed_at', type: 'datetime', nullable: true)]
    private \DateTimeInterface|null $completedAt = null;

    #[ORM\Column(name: 'position_idx', type: 'integer')]
    private int $positionIdx = 1;

    #[ORM\Column(name: 'auto_generated', type: 'boolean')]
    private bool $autoGenerated = false;

    #[ORM\Column(name: 'template_code', type: 'string', length: 60, nullable: true)]
    private string|null $templateCode = null;

    #[ORM\Column(name: 'external_ref', type: 'string', length: 120, nullable: true, unique: true)]
    private string|null $externalRef = null;

    #[ORM\Column(name: 'created_at', type: 'datetime')]
    private \DateTimeInterface $createdAt;

    #[ORM\Column(name: 'updated_at', type: 'datetime')]
    private \DateTimeInterface $updatedAt;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'created_by', referencedColumnName: 'id')]
    private User $creator;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'assigned_to', referencedColumnName: 'id')]
    private User $assignee;
    


    #[ORM\OneToMany(targetEntity: AdminTaskHistory::class, mappedBy: 'task')]
    private Collection $history;

    public function __construct()
    {
        $this->history = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;
        return $this;
    }

    public function getDescription(): string|null
    {
        return $this->description;
    }

    public function setDescription(string|null $description): static
    {
        $this->description = $description;
        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;
        return $this;
    }

    public function getPriority(): string
    {
        return $this->priority;
    }

    public function setPriority(string $priority): static
    {
        $this->priority = $priority;
        return $this;
    }

    public function getTags(): string|null
    {
        return $this->tags;
    }

    public function setTags(string|null $tags): static
    {
        $this->tags = $tags;
        return $this;
    }

    public function getDueDate(): \DateTimeInterface|null
    {
        return $this->dueDate;
    }

    public function setDueDate(\DateTimeInterface|null $dueDate): static
    {
        $this->dueDate = $dueDate;
        return $this;
    }

    public function getStarsEarned(): int
    {
        return $this->starsEarned;
    }

    public function setStarsEarned(int $starsEarned): static
    {
        $this->starsEarned = $starsEarned;
        return $this;
    }

    public function getCompletedAt(): \DateTimeInterface|null
    {
        return $this->completedAt;
    }

    public function setCompletedAt(\DateTimeInterface|null $completedAt): static
    {
        $this->completedAt = $completedAt;
        return $this;
    }

    public function getPositionIdx(): int
    {
        return $this->positionIdx;
    }

    public function setPositionIdx(int $positionIdx): static
    {
        $this->positionIdx = $positionIdx;
        return $this;
    }

    public function getAutoGenerated(): bool
    {
        return $this->autoGenerated;
    }

    public function setAutoGenerated(bool $autoGenerated): static
    {
        $this->autoGenerated = $autoGenerated;
        return $this;
    }

    public function getTemplateCode(): string|null
    {
        return $this->templateCode;
    }

    public function setTemplateCode(string|null $templateCode): static
    {
        $this->templateCode = $templateCode;
        return $this;
    }

    public function getExternalRef(): string|null
    {
        return $this->externalRef;
    }

    public function setExternalRef(string|null $externalRef): static
    {
        $this->externalRef = $externalRef;
        return $this;
    }

    public function getCreatedAt(): \DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getUpdatedAt(): \DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): static
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    public function getCreator(): User
    {
        return $this->creator;
    }

    public function setCreator(User $creator): static
    {
        $this->creator = $creator;
        return $this;
    }

    public function getAssignee(): User
    {
        return $this->assignee;
    }

    public function setAssignee(User $assignee): static
    {
        $this->assignee = $assignee;
        return $this;
    }

    public function getHistory(): Collection
    {
        return $this->history;
    }

    public function addHistory(AdminTaskHistory $history): static
    {
        if (!$this->history->contains($history)) {
            $this->history->add($history);
        }
        return $this;
    }

    public function removeHistory(AdminTaskHistory $history): static
    {
        $this->history->removeElement($history);
        return $this;
    }

    public function isAutoGenerated(): ?bool
    {
        return $this->autoGenerated;
    }
}
