<?php

namespace ContainerVWXgpie;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D7J7PlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d7J_7Pl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorie' => ['privates', '.errored..service_locator.d7J_7Pl.App\\Entity\\Categorie\\Categorie', NULL, 'Cannot autowire service ".service_locator.d7J_7Pl": it needs an instance of "App\\Entity\\Categorie\\Categorie" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categorie' => 'App\\Entity\\Categorie\\Categorie',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.d7J_7Pl'])) {
            return $container->privates['.service_locator.d7J_7Pl'];
        }

        return $container->privates['.service_locator.d7J_7Pl'] = $instance;
    }
}
