<?php

namespace ContainerVWXgpie;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JSYgyyfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jSYgyyf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\CategorieController::delete' => ['privates', '.service_locator.d7J_7Pl', 'get_ServiceLocator_D7J7PlService', true],
            'App\\Controller\\Admin\\CategorieController::edit' => ['privates', '.service_locator.d7J_7Pl', 'get_ServiceLocator_D7J7PlService', true],
            'App\\Controller\\Admin\\CategorieController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\CategorieController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\CategorieController::show' => ['privates', '.service_locator.Ry.DXQK', 'get_ServiceLocator_Ry_DXQKService', true],
            'App\\Controller\\Admin\\DashboardController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\ItemController::delete' => ['privates', '.service_locator.zjyU_RN', 'get_ServiceLocator_ZjyURNService', true],
            'App\\Controller\\Admin\\ItemController::edit' => ['privates', '.service_locator.zjyU_RN', 'get_ServiceLocator_ZjyURNService', true],
            'App\\Controller\\Admin\\ItemController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\ItemController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\ItemController::show' => ['privates', '.service_locator.hsywqbn', 'get_ServiceLocator_HsywqbnService', true],
            'App\\Controller\\Front\\CategorieController::delete' => ['privates', '.service_locator.d7J_7Pl', 'get_ServiceLocator_D7J7PlService', true],
            'App\\Controller\\Front\\CategorieController::edit' => ['privates', '.service_locator.d7J_7Pl', 'get_ServiceLocator_D7J7PlService', true],
            'App\\Controller\\Front\\CategorieController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Front\\CategorieController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Front\\CategorieController::show' => ['privates', '.service_locator.Ry.DXQK', 'get_ServiceLocator_Ry_DXQKService', true],
            'App\\Controller\\Front\\ItemController::delete' => ['privates', '.service_locator.zjyU_RN', 'get_ServiceLocator_ZjyURNService', true],
            'App\\Controller\\Front\\ItemController::edit' => ['privates', '.service_locator.zjyU_RN', 'get_ServiceLocator_ZjyURNService', true],
            'App\\Controller\\Front\\ItemController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Front\\ItemController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Front\\ItemController::show' => ['privates', '.service_locator.hsywqbn', 'get_ServiceLocator_HsywqbnService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\CategorieController:delete' => ['privates', '.service_locator.d7J_7Pl', 'get_ServiceLocator_D7J7PlService', true],
            'App\\Controller\\Admin\\CategorieController:edit' => ['privates', '.service_locator.d7J_7Pl', 'get_ServiceLocator_D7J7PlService', true],
            'App\\Controller\\Admin\\CategorieController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\CategorieController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\CategorieController:show' => ['privates', '.service_locator.Ry.DXQK', 'get_ServiceLocator_Ry_DXQKService', true],
            'App\\Controller\\Admin\\DashboardController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\ItemController:delete' => ['privates', '.service_locator.zjyU_RN', 'get_ServiceLocator_ZjyURNService', true],
            'App\\Controller\\Admin\\ItemController:edit' => ['privates', '.service_locator.zjyU_RN', 'get_ServiceLocator_ZjyURNService', true],
            'App\\Controller\\Admin\\ItemController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\ItemController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\ItemController:show' => ['privates', '.service_locator.hsywqbn', 'get_ServiceLocator_HsywqbnService', true],
            'App\\Controller\\Front\\CategorieController:delete' => ['privates', '.service_locator.d7J_7Pl', 'get_ServiceLocator_D7J7PlService', true],
            'App\\Controller\\Front\\CategorieController:edit' => ['privates', '.service_locator.d7J_7Pl', 'get_ServiceLocator_D7J7PlService', true],
            'App\\Controller\\Front\\CategorieController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Front\\CategorieController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Front\\CategorieController:show' => ['privates', '.service_locator.Ry.DXQK', 'get_ServiceLocator_Ry_DXQKService', true],
            'App\\Controller\\Front\\ItemController:delete' => ['privates', '.service_locator.zjyU_RN', 'get_ServiceLocator_ZjyURNService', true],
            'App\\Controller\\Front\\ItemController:edit' => ['privates', '.service_locator.zjyU_RN', 'get_ServiceLocator_ZjyURNService', true],
            'App\\Controller\\Front\\ItemController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Front\\ItemController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Front\\ItemController:show' => ['privates', '.service_locator.hsywqbn', 'get_ServiceLocator_HsywqbnService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\CategorieController::delete' => '?',
            'App\\Controller\\Admin\\CategorieController::edit' => '?',
            'App\\Controller\\Admin\\CategorieController::index' => '?',
            'App\\Controller\\Admin\\CategorieController::new' => '?',
            'App\\Controller\\Admin\\CategorieController::show' => '?',
            'App\\Controller\\Admin\\DashboardController::index' => '?',
            'App\\Controller\\Admin\\ItemController::delete' => '?',
            'App\\Controller\\Admin\\ItemController::edit' => '?',
            'App\\Controller\\Admin\\ItemController::index' => '?',
            'App\\Controller\\Admin\\ItemController::new' => '?',
            'App\\Controller\\Admin\\ItemController::show' => '?',
            'App\\Controller\\Front\\CategorieController::delete' => '?',
            'App\\Controller\\Front\\CategorieController::edit' => '?',
            'App\\Controller\\Front\\CategorieController::index' => '?',
            'App\\Controller\\Front\\CategorieController::new' => '?',
            'App\\Controller\\Front\\CategorieController::show' => '?',
            'App\\Controller\\Front\\ItemController::delete' => '?',
            'App\\Controller\\Front\\ItemController::edit' => '?',
            'App\\Controller\\Front\\ItemController::index' => '?',
            'App\\Controller\\Front\\ItemController::new' => '?',
            'App\\Controller\\Front\\ItemController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\CategorieController:delete' => '?',
            'App\\Controller\\Admin\\CategorieController:edit' => '?',
            'App\\Controller\\Admin\\CategorieController:index' => '?',
            'App\\Controller\\Admin\\CategorieController:new' => '?',
            'App\\Controller\\Admin\\CategorieController:show' => '?',
            'App\\Controller\\Admin\\DashboardController:index' => '?',
            'App\\Controller\\Admin\\ItemController:delete' => '?',
            'App\\Controller\\Admin\\ItemController:edit' => '?',
            'App\\Controller\\Admin\\ItemController:index' => '?',
            'App\\Controller\\Admin\\ItemController:new' => '?',
            'App\\Controller\\Admin\\ItemController:show' => '?',
            'App\\Controller\\Front\\CategorieController:delete' => '?',
            'App\\Controller\\Front\\CategorieController:edit' => '?',
            'App\\Controller\\Front\\CategorieController:index' => '?',
            'App\\Controller\\Front\\CategorieController:new' => '?',
            'App\\Controller\\Front\\CategorieController:show' => '?',
            'App\\Controller\\Front\\ItemController:delete' => '?',
            'App\\Controller\\Front\\ItemController:edit' => '?',
            'App\\Controller\\Front\\ItemController:index' => '?',
            'App\\Controller\\Front\\ItemController:new' => '?',
            'App\\Controller\\Front\\ItemController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.jSYgyyf'])) {
            return $container->privates['.service_locator.jSYgyyf'];
        }

        return $container->privates['.service_locator.jSYgyyf'] = $instance;
    }
}
