<?php

namespace ContainerVWXgpie;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ry_DXQKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ry.DXQK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ry.DXQK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorie' => ['privates', '.errored..service_locator.Ry.DXQK.App\\Entity\\Categorie\\Categorie', NULL, 'Cannot autowire service ".service_locator.Ry.DXQK": it needs an instance of "App\\Entity\\Categorie\\Categorie" but this type has been excluded in "config/services.yaml".'],
        ], [
            'categorie' => 'App\\Entity\\Categorie\\Categorie',
        ]);
    }
}
