[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.4
datadir=c:/Users/INES/Desktop/Projet symfony/Esprit-PIDEV-Symfony-3A28-2026-FinTrust/var/mysql84/data
port=3307
bind-address=127.0.0.1
mysqlx=0
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
log-error=c:/Users/INES/Desktop/Projet symfony/Esprit-PIDEV-Symfony-3A28-2026-FinTrust/var/mysql84/logs/error.log
pid-file=c:/Users/INES/Desktop/Projet symfony/Esprit-PIDEV-Symfony-3A28-2026-FinTrust/var/mysql84/mysql84.pid
