<?php

namespace ContainerAAT2xgY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorie2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.d7J_7Pl.App\Entity\Categorie\Categorie' shared service.
     *
     * @return \App\Entity\Categorie\Categorie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.d7J_7Pl": it needs an instance of "App\\Entity\\Categorie\\Categorie" but this type has been excluded in "config/services.yaml".');
    }
}
