<?php

namespace ContainerAAT2xgY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItem2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zjyU_RN.App\Entity\Categorie\Item' shared service.
     *
     * @return \App\Entity\Categorie\Item
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zjyU_RN": it needs an instance of "App\\Entity\\Categorie\\Item" but this type has been excluded in "config/services.yaml".');
    }
}
