<?php
// src/Controller/LoanController/AdminController.php
namespace App\Controller\LoanController;

use App\Entity\Loan\Loan;
use App\Repository\LoanRepository;
use App\Service\LoanService;
use App\Service\RepaymentService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;

#[Route('/admin')]
class AdminController extends AbstractController
{
    private LoanService $loanService;
    private RepaymentService $repaymentService;
    private CsrfTokenManagerInterface $csrfTokenManager;
    private EntityManagerInterface $em;

    public function __construct(
        LoanService $loanService,
        RepaymentService $repaymentService,
        CsrfTokenManagerInterface $csrfTokenManager,
        EntityManagerInterface $em
    ) {
        $this->loanService = $loanService;
        $this->repaymentService = $repaymentService;
        $this->csrfTokenManager = $csrfTokenManager;
        $this->em = $em;
    }

    /**
     * Dashboard with all loans and filters
     */
    #[Route('/dashboard', name: 'admin_dashboard')]
    public function dashboard(LoanRepository $loanRepo, Request $request): Response
    {
        $status = $request->query->get('status', 'all');
        
        $allLoans = $loanRepo->findAllWithUser();
        
        // Filter loans based on status
        $filteredLoans = match($status) {
            'pending' => $loanRepo->findByStatus('PENDING'),
            'active' => $loanRepo->findActiveLoans(),
            'completed' => $loanRepo->findByStatus('COMPLETED'),
            'rejected' => $loanRepo->findByStatus('REJECTED'),
            default => $allLoans,
        };

        return $this->render('admin/dashboard.html.twig', [
            'allLoans' => $allLoans,
            'filteredLoans' => $filteredLoans,
            'currentFilter' => $status,
            'counts' => [
                'all' => count($allLoans),
                'pending' => $loanRepo->countByStatus('PENDING'),
                'active' => $loanRepo->countByStatus('ACTIVE') + $loanRepo->countByStatus('APPROVED'),
                'completed' => $loanRepo->countByStatus('COMPLETED'),
                'rejected' => $loanRepo->countByStatus('REJECTED'),
            ]
        ]);
    }

    /**
     * Approve loan - only changes status to ACTIVE
     */
    #[Route('/loan/{id}/approve', name: 'admin_loan_approve', methods: ['POST'])]
    public function approveLoan(int $id, LoanRepository $loanRepo, Request $request): Response
    {
        // CSRF Validation
        $token = $request->request->get('_token');
        if (!$this->csrfTokenManager->isTokenValid(new \Symfony\Component\Security\Csrf\CsrfToken('approve_loan_' . $id, $token))) {
            $this->addFlash('error', 'Invalid security token');
            return $this->redirectToRoute('admin_dashboard');
        }

        $loan = $loanRepo->find($id);
        
        if (!$loan || $loan->getStatus() !== 'PENDING') {
            $this->addFlash('error', 'Loan not found or already processed');
            return $this->redirectToRoute('admin_dashboard');
        }

        // Simply activate the loan (repayments already generated by user)
        $this->loanService->approveLoan($loan->getLoanId());

        $this->addFlash('success', sprintf(
            'Loan #%d approved and activated successfully', 
            $id
        ));
        
        return $this->redirectToRoute('admin_dashboard');
    }

    /**
     * Reject loan
     */
    #[Route('/loan/{id}/reject', name: 'admin_loan_reject', methods: ['POST'])]
    public function rejectLoan(int $id, LoanRepository $loanRepo, Request $request): Response
    {
        // CSRF Validation
        $token = $request->request->get('_token');
        if (!$this->csrfTokenManager->isTokenValid(new \Symfony\Component\Security\Csrf\CsrfToken('reject_loan_' . $id, $token))) {
            $this->addFlash('error', 'Invalid security token');
            return $this->redirectToRoute('admin_dashboard');
        }

        $loan = $loanRepo->find($id);
        
        if (!$loan || $loan->getStatus() !== 'PENDING') {
            $this->addFlash('error', 'Loan not found or already processed');
            return $this->redirectToRoute('admin_dashboard');
        }

        $this->loanService->rejectLoan($loan->getLoanId());
        
        $this->addFlash('success', 'Loan rejected');
        return $this->redirectToRoute('admin_dashboard');
    }

    /**
     * View loan details and repayment plan
     */
    #[Route('/loan/{id}/review', name: 'admin_loan_review')]
    public function reviewLoan(int $id, LoanRepository $loanRepo): Response
    {
        $loan = $loanRepo->findLoanWithRepayments($id);
        
        if (!$loan) {
            throw $this->createNotFoundException('Loan not found');
        }

        $calculator = [
            'monthlyPayment' => $this->loanService->calculateMonthlyPayment($loan),
            'totalInterest' => $this->loanService->calculateTotalInterest($loan),
            'totalCost' => $this->loanService->calculateMonthlyPayment($loan) * $loan->getDuration(),
        ];

        $stats = $this->loanService->getLoanStats($loan);

        return $this->render('admin/loan_review.html.twig', [
            'loan' => $loan,
            'calculator' => $calculator,
            'stats' => $stats,
            'isPending' => $loan->getStatus() === 'PENDING',
            'isActive' => in_array($loan->getStatus(), ['ACTIVE', 'APPROVED']),
            'isCompleted' => $loan->getStatus() === 'COMPLETED',
            'isRejected' => $loan->getStatus() === 'REJECTED',
        ]);
    }

    /**
     * View detailed repayment history
     */
    #[Route('/loan/{id}/repayments', name: 'admin_loan_repayments')]
    public function viewRepayments(int $id, LoanRepository $loanRepo): Response
    {
        $loan = $loanRepo->findLoanWithRepayments($id);
        
        if (!$loan) {
            throw $this->createNotFoundException('Loan not found');
        }

        $stats = $this->repaymentService->getRepaymentStats($id);
        $nextUnpaid = $this->repaymentService->findNextUnpaid($id);

        return $this->render('admin/repayments.html.twig', [
            'loan' => $loan,
            'repayments' => $loan->getRepayments(),
            'stats' => $stats,
            'nextUnpaid' => $nextUnpaid,
            'calculator' => [
                'monthlyPayment' => $this->loanService->calculateMonthlyPayment($loan),
                'totalInterest' => $this->loanService->calculateTotalInterest($loan),
            ],
        ]);
    }
}