<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGV0Lh9u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGV0Lh9u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGV0Lh9u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGV0Lh9u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGV0Lh9u\App_KernelDevDebugContainer([
    'container.build_hash' => 'GV0Lh9u',
    'container.build_id' => '102d276a',
    'container.build_time' => 1775493926,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGV0Lh9u');
