<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRpBYH9Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRpBYH9Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRpBYH9Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRpBYH9Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRpBYH9Q\App_KernelDevDebugContainer([
    'container.build_hash' => 'RpBYH9Q',
    'container.build_id' => 'a109ca62',
    'container.build_time' => 1775337229,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRpBYH9Q');
