<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPZJ0k8d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPZJ0k8d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPZJ0k8d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPZJ0k8d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPZJ0k8d\App_KernelDevDebugContainer([
    'container.build_hash' => 'PZJ0k8d',
    'container.build_id' => '90565afb',
    'container.build_time' => 1775762407,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPZJ0k8d');
