<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app' => [[], ['_controller' => 'App\\Controller\\LandingPage::index'], [], [['text', '/']], [], [], []],
    'admin_dashboard' => [[], ['_controller' => 'App\\Controller\\LoanController\\AdminController::dashboard'], [], [['text', '/admin/dashboard']], [], [], []],
    'admin_loan_approve' => [['id'], ['_controller' => 'App\\Controller\\LoanController\\AdminController::approveLoan'], [], [['text', '/approve'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/loan']], [], [], []],
    'admin_loan_reject' => [['id'], ['_controller' => 'App\\Controller\\LoanController\\AdminController::rejectLoan'], [], [['text', '/reject'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/loan']], [], [], []],
    'admin_loan_review' => [['id'], ['_controller' => 'App\\Controller\\LoanController\\AdminController::reviewLoan'], [], [['text', '/review'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/loan']], [], [], []],
    'admin_loan_repayments' => [['id'], ['_controller' => 'App\\Controller\\LoanController\\AdminController::viewRepayments'], [], [['text', '/repayments'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/loan']], [], [], []],
    'App\Controller\LandingPage::index' => [[], ['_controller' => 'App\\Controller\\LandingPage::index'], [], [['text', '/']], [], [], []],
    'App\Controller\LoanController\AdminController::dashboard' => [[], ['_controller' => 'App\\Controller\\LoanController\\AdminController::dashboard'], [], [['text', '/admin/dashboard']], [], [], []],
    'App\Controller\LoanController\AdminController::approveLoan' => [['id'], ['_controller' => 'App\\Controller\\LoanController\\AdminController::approveLoan'], [], [['text', '/approve'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/loan']], [], [], []],
    'App\Controller\LoanController\AdminController::rejectLoan' => [['id'], ['_controller' => 'App\\Controller\\LoanController\\AdminController::rejectLoan'], [], [['text', '/reject'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/loan']], [], [], []],
    'App\Controller\LoanController\AdminController::reviewLoan' => [['id'], ['_controller' => 'App\\Controller\\LoanController\\AdminController::reviewLoan'], [], [['text', '/review'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/loan']], [], [], []],
    'App\Controller\LoanController\AdminController::viewRepayments' => [['id'], ['_controller' => 'App\\Controller\\LoanController\\AdminController::viewRepayments'], [], [['text', '/repayments'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/loan']], [], [], []],
];
